stages:
  - deploy

Deploy to stage:
  stage: deploy
  tags:
    - dep
  script:
    - cp $ENV_PROD .env
    - cp $ENV_STAGE .env.docker
    - docker-compose -f docker-compose.yml down
    - docker-compose -f docker-compose.yml up -d --build
